version: '3.8'

services:
  backend:
    build: .
    ports:
      - "9000:9000"
      - "8080:8080"
    volumes:
      - ./money_tracker.db:/app/money_tracker.db
    env_file:
      - .env
    labels:
      # Traefik settings to route traffic to the backend service
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`money.ensa-ai.com`)"  # Replace with your domain
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    restart: unless-stopped

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      # Traefik settings
      - "--api.insecure=true"                    # Enable API dashboard for debugging (disable in production)
      - "--providers.docker=true"                # Enable Docker provider
      - "--entryPoints.web.address=:80"          # HTTP entry point
      - "--entryPoints.websecure.address=:443"   # HTTPS entry point
      - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"  # TLS challenge for Let's Encrypt
      - "--certificatesResolvers.myresolver.acme.email=your-email@example.com"  # Replace with your email
      - "--certificatesResolvers.myresolver.acme.storage=/acme.json"  # Where certificates will be stored
    ports:
      - "80:80"   # HTTP traffic for Let's Encrypt
      - "443:443" # HTTPS traffic for your domain
      - "8080:8080"  # Traefik dashboard (optional, disable in production)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"   # Allows Traefik to discover Docker containers
      - "./acme.json:/acme.json"                       # Store SSL certificates
    restart: unless-stopped
    # Make sure acme.json has the correct permissions
    command: /bin/sh -c "touch /acme.json && chmod 600 /acme.json && traefik"
